// @ts-nocheck
"use client";
import {useEffect,useMemo,useState} from "react";
import {motion} from "framer-motion";
import {useWorldStore} from "../lib/store";

const sections=["HOME","WARRIOR","JOURNEY","SKILLS","SHADOW ARTS","MISSIONS","VICTORIES","CONTACT","ENDING"];
const cyberLines=["INITIALIZING CYBER OPS...","KALI LINUX // ONLINE","ETHICAL HACKING // READY","OSINT // ACTIVE","SQL // READY","DARK WEB / DARKNET // EXPOSURE","MODE // OBSERVATION ONLY"];

export default function Overlay(){
 const p=useWorldStore(s=>s.progress),setP=useWorldStore(s=>s.setProgress);
 const [line,setLine]=useState(0),[scramble,setScramble]=useState("");
 const rain=useMemo(()=>Array.from({length:30},(_,i)=>({left:(i*3.6)%100,delay:(i%11)*.32,duration:4+(i%7)})),[]);
 useEffect(()=>{const id=setInterval(()=>setLine(v=>(v+1)%cyberLines.length),1900);return()=>clearInterval(id)},[]);
 useEffect(()=>{const target=cyberLines[line];let n=0;const chars="01XZ#$%<>/";const id=setInterval(()=>{n++;setScramble(target.split("").map((c,i)=>i<n?c:chars[Math.floor(Math.random()*chars.length)]).join(""));if(n>=target.length)clearInterval(id)},20);return()=>clearInterval(id)},[line]);
 useEffect(()=>{const on=()=>{const m=document.documentElement.scrollHeight-innerHeight;setP(m?scrollY/m:0)};addEventListener("scroll",on,{passive:true});on();return()=>removeEventListener("scroll",on)},[setP]);
 const jump=i=>{const m=document.documentElement.scrollHeight-innerHeight;scrollTo({top:m*(i/(sections.length-1)),behavior:"smooth"})};
 return <div className="relative z-20 pointer-events-none">
  <nav className="pointer-events-auto fixed left-1/2 top-4 z-50 -translate-x-1/2 pixel-nav"><div className="flex max-w-[96vw] overflow-x-auto">{sections.map((s,i)=><button key={s} onClick={()=>jump(i)}>{s}</button>)}</div></nav>
  <div className="fixed left-4 top-5 z-50 pixel-hud"><div>PLAYER 01</div><div>LEVEL 01 // ORIGIN</div><div className="status-online">STATUS: ONLINE</div><div className="xp-track"><span style={{width:`${p*100}%`}}/></div><div>XP {Math.round(p*999).toString().padStart(3,"0")} / 999</div></div>
  <main className="min-h-[900vh]">
   <section className="hero-section min-h-screen grid place-items-center px-6 text-center"><div className="hero-core max-w-6xl"><div className="pixel-kicker">PLAYER 01 // DIGITAL WARRIOR // ONLINE</div><h1 className="pixel-title fire-text mt-5">SATYAM<br/>MISHRA</h1><p className="pixel-role mt-7">AI &amp; Data Science Student @ IIT Jodhpur</p><p className="pixel-copy hero-copy mx-auto mt-5 max-w-3xl">Exploring AI, Data Science, Machine Learning, Web Development and Cybersecurity while building practical technology.</p><div className="hero-loadout mx-auto mt-7"><span>AI / DATA</span><span>WEB DEV</span><span className="hot">CYBERSECURITY</span><span className="hot">KALI LINUX</span></div><div className="pointer-events-auto mt-9 flex flex-wrap justify-center gap-3"><PixelButton onClick={()=>jump(1)}>ENTER MY WORLD</PixelButton><PixelButton onClick={()=>jump(5)} secondary>VIEW MY QUEST</PixelButton></div><div className="hero-scroll mt-10"><span className="scroll-arrow">▼</span> SCROLL TO ENTER THE WORLD <span className="scroll-arrow">▼</span></div></div></section>
   <section className="min-h-screen flex items-center px-6 md:px-16"><Card k="THE WARRIOR" t="AI. DATA. SECURITY. BUILD." b="IIT Jodhpur • AI & Data Science • AI/ML • Web Development • Cybersecurity • Hackathons • Gaganyaan • AWS SBG technical leadership • Building practical solutions"/></section>
   <section data-journey className="min-h-screen flex items-center px-6 md:px-16"><Card k="THE JOURNEY // MAJOR MILESTONES" t="FROM CAMPUS TO SPACE" b="IIT Jodhpur • Gaganyaan internship • ISRO Hackathon participant • Deloitte Australia cybersecurity job simulation via Forage • AWS SBG IIT Jodhpur Technical Co-Lead • Smart India Hackathon participant"/></section>
   <section className="min-h-screen flex items-center px-6 md:px-16"><div className="w-full max-w-6xl"><div className="pixel-kicker">SKILL TREE // UNLOCKED</div><h2 className="pixel-section-title">ABILITIES</h2><div className="skill-grid mt-9">{[["AI & DATA",["AI","Data Science","Machine Learning","Statistics & Probability"]],["PROGRAMMING",["Python","DSA","SQL"]],["WEB",["HTML","CSS","JavaScript","Responsive Design"]],["CYBERSECURITY",["CYBERSECURITY","ETHICAL HACKING","KALI LINUX","OSINT"]],["TOOLS",["Git","GitHub","Vercel"]]].map(([h,a])=><div className="glass skill-card" key={h as string}><div className="node-core"/><div className="hud text-cyan-200 text-[10px]">{h}</div><div className="mt-4 flex flex-wrap gap-2">{(a as string[]).map(x=><span key={x} className={x.includes("KALI")||x.includes("OSINT")||x==="SQL"?"skill-hot":"skill-chip"}>{x}</span>)}</div></div>)}</div></div></section>
   <section data-cyber className="min-h-screen flex items-center justify-end px-6 md:px-16 relative overflow-hidden cyber-realm"><div className="matrix absolute inset-0">{rain.map((r,i)=><span key={i} style={{left:`${r.left}%`,animationDelay:`${r.delay}s`,animationDuration:`${r.duration}s`}}>0101XOSINT</span>)}</div><div className="cyber-scanlines absolute inset-0"/><div className="cyber-panel-wrap pointer-events-auto"><div className="cyber-topbar"><span className="dot red"/><span className="dot green"/><span className="dot amber"/><b>SHADOW ARTS // CYBER OPS</b></div><div className="cyber-panel"><div className="cyber-glitch">{scramble}<span className="cursor">_</span></div><div className="cyber-status"><span>ACCESS <i/></span><span>TRACE <i/></span><span>SIGNAL <i/></span></div><div className="cyber-skills"><strong>PRIMARY LOADOUT</strong><div>KALI LINUX</div><div>ETHICAL HACKING</div><div>OSINT</div><div>SQL</div><div>DARK WEB / DARKNET EXPOSURE</div></div><p className="cyber-note">Visual-only cyber aesthetic. No exploit code or operational instructions.</p></div></div></section>
   <section className="min-h-screen flex items-center px-6 md:px-16"><div className="w-full max-w-5xl"><div className="pixel-kicker">MISSIONS // ARCHIVE</div><h2 className="pixel-section-title">BUILD LOG</h2><div className="grid md:grid-cols-2 gap-4 mt-9"><div className="glass mission-placeholder"><div className="hud text-cyan-200 text-[9px]">MISSION SLOT 01</div><h3>DETAILS PENDING</h3><p className="pixel-copy">Project information will be added when finalized.</p></div><div className="glass mission-placeholder"><div className="hud text-white/40 text-[9px]">NEXT MISSION</div><h3>LOCKED</h3><p className="pixel-copy">A new mission will appear here.</p></div></div></div></section>
   <section className="min-h-screen flex items-center px-6 md:px-16"><div className="w-full max-w-5xl"><div className="pixel-kicker">VICTORIES // VERIFIED MILESTONES</div><h2 className="pixel-section-title">ACHIEVEMENTS</h2><div className="grid md:grid-cols-2 gap-3 mt-9">{["Gaganyaan Internship","ISRO Hackathon Participant","Deloitte Australia / Forage Cybersecurity Job Simulation","Lean Six Sigma AI — Yellow Belt","AWS SBG IIT Jodhpur — Technical Co-Lead","Smart India Hackathon — Participant"].map((x,i)=><motion.div whileHover={{y:-5}} className={i===0?"glass achievement-card achievement-primary":"glass achievement-card"} key={x}><div className="hud text-orange-300 text-[9px]">ACHIEVEMENT {String(i+1).padStart(2,"0")}</div><h3>{x}</h3></motion.div>)}</div><p className="pixel-muted mt-5">Secondary: IIT Jodhpur chess team for an inter-college competition.</p></div></section>
   <section data-final className="min-h-screen flex items-center justify-center px-6 text-center"><div><div className="pixel-kicker">FINAL BATTLE // CONTACT</div><h2 className="pixel-section-title">THE JOURNEY<br/>DOESN&apos;T END HERE.</h2><p className="pixel-copy">Let&apos;s build something meaningful.</p><div className="pointer-events-auto mt-9 flex flex-wrap justify-center gap-3"><a className="pixel-btn" href="#">GITHUB // EDIT</a><a className="pixel-btn" href="#">LINKEDIN // EDIT</a><a className="pixel-btn primary" href="mailto:your-email@example.com">EMAIL // EDIT</a></div></div></section>
   <section data-ending className="min-h-screen grid place-items-center px-6 text-center"><div><div className="pixel-kicker">NEXT LEVEL LOADING…</div><h3 className="pixel-section-title">SATYAM MISHRA</h3><p className="pixel-tagline">BUILD. LEARN. INNOVATE.</p><button className="pointer-events-auto pixel-btn mt-9" onClick={()=>jump(0)}>RESTART QUEST</button></div></section>
  </main>
 </div>;
}
function PixelButton({children,onClick,secondary=false}){return <motion.button whileHover={{y:-3,scale:1.03}} whileTap={{scale:.98}} onClick={onClick} className={secondary?"pixel-btn":"pixel-btn primary"}>{children}</motion.button>}
function Card({k,t,b}){return <motion.div initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="glass info-card"><div className="hud text-orange-300 text-xs">{k}</div><h2 className="pixel-card-title">{t}</h2><p className="pixel-copy mt-5">{b}</p></motion.div>}
