// @ts-nocheck
"use client";
import {useEffect,useMemo,useState} from "react";
import {motion} from "framer-motion";
import {useWorldStore} from "../lib/store";

const sections=["HOME","WARRIOR","JOURNEY","SKILLS","SHADOW ARTS","MISSIONS","VICTORIES","CONTACT","ENDING"];

export default function Overlay(){
  const p=useWorldStore(s=>s.progress),setP=useWorldStore(s=>s.setProgress);const[term,setTerm]=useState("");
  const rain=useMemo(()=>Array.from({length:26},(_,i)=>({left:i*4,delay:i%8,dur:4+i%5})),[]);
  useEffect(()=>{let i=0;const id=setInterval(()=>{i++;setTerm("shadow@kali:~$ osint --status".slice(0,i));if(i>=28)clearInterval(id)},45);const f=()=>{const m=document.documentElement.scrollHeight-innerHeight;setP(m?scrollY/m:0)};addEventListener("scroll",f,{passive:true});f();return()=>{clearInterval(id);removeEventListener("scroll",f)}},[setP]);
  const jump=(i:number)=>{const m=document.documentElement.scrollHeight-innerHeight;scrollTo({top:m*i/8,behavior:"smooth"})};
  return <div className="relative z-10 pointer-events-none">
    <nav className="pointer-events-auto fixed top-4 left-1/2 -translate-x-1/2 z-40 flex max-w-[97vw] overflow-x-auto rounded-sm glass px-1">{sections.map((s,i)=><button key={s} onClick={()=>jump(i)} className="whitespace-nowrap px-3 py-2 text-[8px] tracking-widest text-white/60 hover:bg-orange-500/10 hover:text-orange-300">{s}</button>)}</nav>
    <div className="fixed left-5 top-5 z-40 hud text-[9px] text-white/55">PLAYER 01<br/>LEVEL 01 — ORIGIN<br/><span className="text-orange-300">STATUS: ONLINE</span><div className="mt-2 h-1 w-36 bg-white/10"><div className="h-full bg-orange-400" style={{width:p*100+"%"}}/></div><div className="mt-1 text-[7px] text-white/30">XP {String(Math.round(p*1000)).padStart(4,"0")}</div></div>
    <main className="min-h-[900vh]">
      <section className="min-h-screen flex items-center px-6 md:px-16"><div className="max-w-5xl"><p className="hud text-orange-300">PLAYER 01 • ORIGIN</p><h1 className="fire-text text-5xl md:text-[8.5rem] font-black leading-[.88] mt-5">SATYAM<br/>MISHRA</h1><p className="text-xl md:text-2xl mt-8 text-white/85">AI & Data Science Student @ IIT Jodhpur</p><p className="max-w-2xl mt-4 text-white/60 leading-7">Exploring AI, Data Science, Machine Learning, Web Development and Cybersecurity while building practical technology.</p><div className="pointer-events-auto flex gap-3 mt-8 flex-wrap"><Button onClick={()=>jump(1)}>ENTER MY WORLD</Button><Button onClick={()=>jump(5)} secondary>VIEW MY QUEST</Button></div></div></section>
      <section className="min-h-screen flex items-center px-6 md:px-16"><Card k="THE WARRIOR" t="Technology. Curiosity. Practical creation." b="IIT Jodhpur • AI & Data Science • AI/ML • Web Development • Cybersecurity • Hackathons • Gaganyaan • Technology leadership • Building practical solutions"/></section>
      <section className="min-h-screen flex items-center px-6 md:px-16"><Card k="THE JOURNEY • SPACE MISSION" t="Six milestones along the quest." b="IIT Jodhpur • Gaganyaan internship • ISRO Hackathon participant • Deloitte Australia cybersecurity job simulation via Forage • AWS SBG IIT Jodhpur Technical Co-Lead • Smart India Hackathon participant"/></section>
      <section className="min-h-screen flex items-center px-6 md:px-16"><div className="w-full max-w-6xl"><p className="hud text-orange-300">SKILL TREE</p><h2 className="text-4xl md:text-7xl font-black mt-4">UNLOCKED ABILITIES</h2><div className="skill-grid mt-10">{[["AI & DATA",["AI","Data Science","Machine Learning","Statistics & Probability"]],["PROGRAMMING",["Python","DSA","SQL"]],["WEB",["HTML","CSS","JavaScript","Responsive Design"]],["CYBERSECURITY",["CYBERSECURITY","ETHICAL HACKING","KALI LINUX","OSINT"]],["TOOLS",["Git","GitHub","Vercel"]]].map(([h,a])=><div className="glass rounded-2xl p-5" key={h as string}><p className="hud text-cyan-200 text-[10px]">{h}</p><div className="flex flex-wrap gap-2 mt-4">{(a as string[]).map(x=><span key={x} className="rounded-sm bg-white/5 border border-white/10 px-3 py-2 text-xs">{x}</span>)}</div></div>)}</div></div></section>
      <section className="min-h-screen flex items-center justify-center px-6 md:px-16 relative overflow-hidden"><div className="matrix absolute inset-0 opacity-35">{rain.map((x,i)=><span key={i} style={{left:x.left+"%",animationDelay:x.delay+"s",animationDuration:x.dur+"s"}}>01XKALI</span>)}</div><div className="cyber-hero relative z-10 w-full max-w-5xl p-7 md:p-12"><div className="grid md:grid-cols-[1.15fr_.85fr] gap-10 items-center"><div><p className="cyber-label">SHADOW ARTS • CYBERSECURITY</p><h2 className="cyber-big mt-5">CYBER<br/>OPS</h2><p className="mt-6 max-w-xl text-white/65 leading-7">Cybersecurity, ethical hacking, Kali Linux and OSINT are a major part of the toolkit. SQL knowledge is also part of the stack.</p><div className="mt-7 flex flex-wrap gap-3"><span className="cyber-tag hot">KALI LINUX</span><span className="cyber-tag hot">ETHICAL HACKING</span><span className="cyber-tag">CYBERSECURITY</span><span className="cyber-tag">OSINT</span><span className="cyber-tag">SQL</span></div><p className="mt-5 text-[10px] text-white/35">Dark-web / darknet awareness and exposure — presented without operational details.</p></div><div className="rounded-sm border-2 border-cyan-300/25 bg-black/70 p-5 font-mono text-xs leading-7 text-cyan-200 shadow-[5px_5px_0_#02151a]"><div className="text-white/25">┌── SATYAM // SHADOW TERMINAL ──┐</div><div className="mt-3">{term}<span className="animate-pulse">▌</span></div><div className="mt-3 text-white/55">STATUS : <span className="text-emerald-300">ONLINE</span></div><div className="text-white/55">MODULES:</div><div className="text-orange-300">KALI • OSINT • HACKING • SQL</div></div></div></div></section>
      <section className="min-h-screen flex items-center px-6 md:px-16"><Card k="MISSIONS" t="MISSION 01 — AEROAI" b="AI + aerospace concept. Description, stack and links remain editable placeholders while exact project details are finalized. NEXT MISSION: LOCKED SLOT"/></section>
      <section className="min-h-screen flex items-center px-6 md:px-16"><div className="w-full max-w-5xl"><p className="hud text-orange-300">VICTORIES</p><h2 className="text-4xl md:text-7xl font-black mt-4">MILESTONES</h2><div className="grid md:grid-cols-2 gap-3 mt-10">{["Gaganyaan Internship","ISRO Hackathon Participant","Deloitte Australia / Forage Cybersecurity Job Simulation","Lean Six Sigma AI — Yellow Belt","AWS SBG IIT Jodhpur — Technical Co-Lead","Smart India Hackathon — Participant"].map((x,i)=><motion.div whileHover={{y:-4}} className={i===0?"glass rounded-sm border-orange-400/60 p-7 md:col-span-2":"glass rounded-sm p-6"} key={x}><p className="hud text-orange-300 text-[9px]">ACHIEVEMENT {String(i+1).padStart(2,"0")}</p><h3 className="font-black text-xl mt-2">{x}</h3></motion.div>)}</div><p className="text-xs text-white/35 mt-5">Secondary: IIT Jodhpur chess team for an inter-college competition.</p></div></section>
      <section className="min-h-screen flex items-center justify-center text-center px-6"><div className="max-w-4xl"><p className="hud text-orange-300">FINAL BATTLE</p><h2 className="text-4xl md:text-8xl font-black mt-5">THE JOURNEY<br/>DOESN&apos;T END HERE.</h2><p className="text-white/55 mt-5">Let&apos;s build something meaningful.</p><div className="flex gap-3 justify-center mt-8 pointer-events-auto flex-wrap"><a href="#" className="glass rounded-sm px-6 py-3 text-xs">GITHUB — EDIT LINK</a><a href="#" className="glass rounded-sm px-6 py-3 text-xs">LINKEDIN — EDIT LINK</a><a href="mailto:your-email@example.com" className="bg-orange-500 text-black rounded-sm px-6 py-3 text-xs font-bold">EMAIL — EDIT LINK</a></div></div></section>
      <section className="min-h-screen flex items-center justify-center text-center px-6"><div><p className="hud text-orange-300">NEXT LEVEL LOADING…</p><h3 className="text-5xl md:text-8xl font-black mt-5">SATYAM MISHRA</h3><p className="tracking-[.28em] text-white/40 mt-4">BUILD. LEARN. INNOVATE.</p><button className="pointer-events-auto mt-10 border-2 border-white/15 rounded-sm px-6 py-3 text-xs" onClick={()=>jump(0)}>RESTART QUEST</button></div></section>
    </main></div>
}
function Button({children,onClick,secondary=false}:{children:React.ReactNode;onClick:()=>void;secondary?:boolean}){return <motion.button whileHover={{y:-3,scale:1.03}} whileTap={{scale:.98}} onClick={onClick} className={secondary?"glass rounded-sm px-6 py-3 text-xs font-bold tracking-widest":"bg-orange-500 text-black rounded-sm px-6 py-3 text-xs font-bold tracking-widest"}>{children}</motion.button>}
function Card({k,t,b}:{k:string;t:string;b:string}){return <motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="glass relative z-10 max-w-2xl rounded-sm p-7 md:p-10"><p className="hud text-orange-300 text-xs">{k}</p><h2 className="text-3xl md:text-5xl font-black mt-5">{t}</h2><p className="text-white/60 leading-7 mt-5">{b}</p></motion.div>}
