// @ts-nocheck
"use client";
import {Canvas,useFrame,useThree} from "@react-three/fiber";
import {Environment,Stars} from "@react-three/drei";
import {EffectComposer,Bloom,DepthOfField,ChromaticAberration,Vignette,Noise} from "@react-three/postprocessing";
import gsap from "gsap"; import {ScrollTrigger} from "gsap/ScrollTrigger"; import * as THREE from "three"; import {useEffect,useMemo,useRef,useState} from "react"; import {useWorldStore} from "../lib/store";
gsap.registerPlugin(ScrollTrigger);

function Terrain(){const geo=useMemo(()=>{const g=new THREE.PlaneGeometry(70,190,60,140),p=g.attributes.position;for(let i=0;i<p.count;i++){const x=p.getX(i),y=p.getY(i);p.setZ(i,Math.sin(x*.25)*.7+Math.sin(y*.11)*.6+Math.sin((x+y)*.05)*.7)}g.computeVertexNormals();return g},[]);return <mesh geometry={geo} rotation-x={-Math.PI/2} position={[0,-1,-55]} receiveShadow><meshStandardMaterial color="#160d0a" roughness={1}/></mesh>}
function Mountains(){return <group position={[0,2,-85]}>{Array.from({length:14},(_,i)=><mesh key={i} position={[(i-7)*9,6+(i%4)*2,-(i%3)*3]}><coneGeometry args={[8,12+(i%4)*3,6]}/><meshStandardMaterial color="#05070a" roughness={1}/></mesh>)}</group>}
function Fire(){const mat=useRef<THREE.ShaderMaterial>(null);const light=useRef<THREE.PointLight>(null);useFrame(({clock})=>{const t=clock.elapsedTime;if(mat.current)mat.current.uniforms.uTime.value=t;if(light.current)light.current.intensity=7+Math.sin(t*9)*1.5});return <group position={[0,0,-32]}><pointLight ref={light} color="#ff4b18" distance={45} intensity={8}/><mesh position={[0,3,0]} scale={[6,8,2]}><planeGeometry args={[1,1,32,32]}/><shaderMaterial ref={mat} transparent depthWrite={false} blending={THREE.AdditiveBlending} uniforms={{uTime:{value:0}}} vertexShader={`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`} fragmentShader={`uniform float uTime;varying vec2 vUv;float h(vec2 p){return fract(sin(dot(p,vec2(12.8,78.2)))*43758.5);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+vec2(1)),f.x),f.y);}void main(){float q=n(vUv*vec2(5.,4.)+vec2(0.,-uTime*1.5));float a=smoothstep(.05,.8,(1.-vUv.y)+q*.55)*smoothstep(.03,.25,vUv.x)*smoothstep(.03,.25,1.-vUv.x);vec3 c=mix(vec3(.35,.01,0),vec3(1,.18,.01),a);c=mix(c,vec3(1,.85,.3),smoothstep(.55,.9,a));gl_FragColor=vec4(c,a);}`}/><mesh position={[0,.8,-.5]}><sphereGeometry args={[2.4,20,12]}/><meshStandardMaterial color="#ff5b17" emissive="#ff2600" emissiveIntensity={5}/></mesh></group>}
function Embers(){const ref=useRef<THREE.InstancedMesh>(null),dummy=useMemo(()=>new THREE.Object3D(),[]),count=500;const data=useMemo(()=>Array.from({length:count},()=>({x:(Math.random()-.5)*45,y:Math.random()*18,z:-Math.random()*155,s:.03+Math.random()*.08})),[]);useFrame(({clock})=>{if(!ref.current||useWorldStore.getState().reduced)return;data.forEach((v,i)=>{v.y+=.025;if(v.y>19)v.y=-1;v.x+=Math.sin(clock.elapsedTime+i)*.001;dummy.position.set(v.x,v.y,v.z);dummy.scale.setScalar(v.s);dummy.updateMatrix();ref.current!.setMatrixAt(i,dummy.matrix)});ref.current.instanceMatrix.needsUpdate=true});return <instancedMesh ref={ref} args={[undefined,undefined,count]}><sphereGeometry args={[1,5,5]}/><meshBasicMaterial color="#ff6330"/></instancedMesh>}
function Gate({z}:{z:number}){const l=useRef<THREE.Group>(null),r=useRef<THREE.Group>(null);useEffect(()=>{const t=ScrollTrigger.create({trigger:document.body,start:"top top",end:"bottom bottom",scrub:1,onUpdate:s=>{const start=Math.max(Math.min(Math.abs(z)/180-.06,.8),0),o=THREE.MathUtils.clamp((s.progress-start)/.1,0,1);if(l.current)l.current.rotation.y=.8*o;if(r.current)r.current.rotation.y=-.8*o}});return()=>t.kill()},[z]);return <group position={[0,3,z]}>{[-1,1].map(s=><mesh key={s} position={[s*5,0,0]} castShadow><cylinderGeometry args={[.7,.9,12,10]}/><meshStandardMaterial color="#4a140a" emissive="#300b05" emissiveIntensity={1}/></mesh>)}<mesh position={[0,8,0]}><boxGeometry args={[14,1,1]}/><meshStandardMaterial color="#741c0b" emissive="#3c0d05" emissiveIntensity={1}/></mesh><group ref={l} position={[-3.2,4.5,0]}><mesh><boxGeometry args={[4.6,7,.4]}/><meshStandardMaterial color="#45120a"/></mesh></group><group ref={r} position={[3.2,4.5,0]}><mesh><boxGeometry args={[4.6,7,.4]}/><meshStandardMaterial color="#45120a"/></mesh></group></group>}
function Samurai(){return <group position={[4,-.8,-42]}><mesh position={[0,2.3,0]} castShadow><sphereGeometry args={[.65,8,6]}/><meshStandardMaterial color="#15171b" metalness={.5}/></mesh><mesh position={[0,1.2,0]} castShadow><cylinderGeometry args={[.75,.9,1.8,8]}/><meshStandardMaterial color="#17191f" metalness={.4}/></mesh><mesh position={[-.55,.2,0]} rotation-z={-.12}><capsuleGeometry args={[.16,1.5,5,8]}/><meshStandardMaterial color="#24262b"/></mesh><mesh position={[.55,.2,0]} rotation-z={.12}><capsuleGeometry args={[.16,1.5,5,8]}/><meshStandardMaterial color="#24262b"/></mesh></group>}
function Camera(){const {camera}=useThree();const reduced=useWorldStore(s=>s.reduced);useEffect(()=>{if(reduced)return;const state={p:0};const t=gsap.to(state,{p:1,ease:"none",scrollTrigger:{trigger:document.body,start:"top top",end:"bottom bottom",scrub:1,onUpdate:s=>useWorldStore.getState().setProgress(s.progress)},onUpdate:()=>{camera.position.z=5-state.p*145}});return()=>{t.kill();t.scrollTrigger?.kill()}},[camera,reduced]);useFrame(()=>{if(!reduced){camera.position.x=THREE.MathUtils.lerp(camera.position.x,0,.04);camera.position.y=THREE.MathUtils.lerp(camera.position.y,2.2,.04)}});return null}
function Scene(){return <><color attach="background" args={["#020306"]}/><fogExp2 attach="fog" args={["#09070a",.034]}/><ambientLight intensity={.18}/><directionalLight position={[-8,15,8]} intensity={.5} color="#9aaed0"/><Environment preset="night"/><Stars radius={120} depth={90} count={2200} factor={1.5} fade speed={.12}/><mesh position={[18,22,-65]}><sphereGeometry args={[2.4,24,16]}/><meshBasicMaterial color="#dbe4ff"/></mesh><Terrain/><Mountains/><Fire/><Embers/><Samurai/><Gate z={-8}/><Gate z={-55}/><Gate z={-105}/><Gate z={-142}/><Camera/><EffectComposer><Bloom intensity={1.2} luminanceThreshold={.5} mipmapBlur/><DepthOfField focusDistance={.02} focalLength={.035} bokehScale={2}/><ChromaticAberration offset={new THREE.Vector2(.0003,.0003)}/><Vignette darkness={.72}/><Noise opacity={.07}/></EffectComposer></>}
export default function World(){const[ready,setReady]=useState(false);useEffect(()=>{useWorldStore.getState().setReduced(matchMedia("(prefers-reduced-motion:reduce)").matches);setReady(true)},[]);return ready?<div className="fixed inset-0 z-0"><Canvas shadows dpr={[1,1.5]} camera={{position:[0,2.2,5],fov:55}} gl={{antialias:true}} onCreated={({gl})=>{gl.toneMapping=THREE.ACESFilmicToneMapping;gl.toneMappingExposure=1.05}}><Scene/></Canvas></div>:<div className="fixed inset-0 z-50 grid place-items-center bg-black hud text-orange-300">FORGING THE WORLD…</div>}